In [1]:
import requests, pandas as pd
r = requests.get("https://api.openf1.org/v1/sessions?year=2024&session_name=Race")
df = pd.DataFrame(r.json())
df.head()

,session_key,session_type,session_name,date_start,date_end,meeting_key,circuit_key,circuit_short_name,country_key,country_code,country_name,location,gmt_offset,year,is_cancelled
0,9472,Race,Race,2024-03-02T15:00:00+00:00,2024-03-02T17:00:00+00:00,1229,63,Sakhir,36,BRN,Bahrain,Sakhir,03:00:00,2024,False
1,9480,Race,Race,2024-03-09T17:00:00+00:00,2024-03-09T19:00:00+00:00,1230,149,Jeddah,153,KSA,Saudi Arabia,Jeddah,03:00:00,2024,False
2,9488,Race,Race,2024-03-24T04:00:00+00:00,2024-03-24T06:00:00+00:00,1231,10,Melbourne,5,AUS,Australia,Melbourne,11:00:00,2024,False
3,9496,Race,Race,2024-04-07T05:00:00+00:00,2024-04-07T07:00:00+00:00,1232,46,Suzuka,4,JPN,Japan,Suzuka,09:00:00,2024,False
4,9673,Race,Race,2024-04-21T07:00:00+00:00,2024-04-21T09:00:00+00:00,1233,49,Shanghai,53,CHN,China,Shanghai,08:00:00,2024,False

In [2]:
df.columns            # all the column names
len(df)               # how many races
df[["country_name", "circuit_short_name", "date_start", "session_key"]]

,country_name,circuit_short_name,date_start,session_key
0,Bahrain,Sakhir,2024-03-02T15:00:00+00:00,9472
1,Saudi Arabia,Jeddah,2024-03-09T17:00:00+00:00,9480
2,Australia,Melbourne,2024-03-24T04:00:00+00:00,9488
3,Japan,Suzuka,2024-04-07T05:00:00+00:00,9496
4,China,Shanghai,2024-04-21T07:00:00+00:00,9673
5,United States,Miami,2024-05-05T20:00:00+00:00,9507
6,Italy,Imola,2024-05-19T13:00:00+00:00,9515
7,Monaco,Monte Carlo,2024-05-26T13:00:00+00:00,9523
8,Canada,Montreal,2024-06-09T18:00:00+00:00,9531
9,Spain,Catalunya,2024-06-23T13:00:00+00:00,9539
10,Austria,Spielberg,2024-06-30T13:00:00+00:00,9550
11,United Kingdom,Silverstone,2024-07-07T14:00:00+00:00,9558
12,Hungary,Hungaroring,2024-07-21T13:00:00+00:00,9566
13,Belgium,Spa-Francorchamps,2024-07-28T13:00:00+00:00,9574
14,Netherlands,Zandvoort,2024-08-25T13:00:00+00:00,9582
15,Italy,Monza,2024-09-01T13:00:00+00:00,9590
16,Azerbaijan,Baku,2024-09-15T11:00:00+00:00,9598
17,Singapore,Singapore,2024-09-22T12:00:00+00:00,9606
18,United States,Austin,2024-10-20T19:00:00+00:00,9617
19,Mexico,Mexico City,2024-10-27T20:00:00+00:00,9625
20,Brazil,Interlagos,2024-11-03T15:30:00+00:00,9636
21,United States,Las Vegas,2024-11-24T06:00:00+00:00,9644
22,Qatar,Lusail,2024-12-01T16:00:00+00:00,9655
23,United Arab Emirates,Yas Marina Circuit,2024-12-08T13:00:00+00:00,9662

In [5]:
italy = df[df["country_name"] == "Italy"]
italy

italy[["circuit_short_name", "date_start", "session_key"]]

key = italy["session_key"].iloc[0]
key

np.int64(9515)